In [1]:
import numpy as np


In [2]:
#creation of numpy array

x = np.array([1,2,3,4,5])
print(x)
print(type(x))   #ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# shape and size

print(x.size)   # length or total no. of elements
print(x.shape)  #dimentions here it means it has 5 rows and no columns
print("dimension", x.ndim)  #no. of dimention here it is 1D


5
(5,)
dimension 1


In [4]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)

# shape and size
print(x2d.size)   # length or total no. of elements
print(x2d.shape)  #dimentions here it means no. of rows and no. of columns
print("dimension", x2d.ndim)  #no. of dimention

[[1 2 3]
 [4 5 6]]
6
(2, 3)
dimension 2


In [5]:
#here random gives the values randomly in matrix form
x25= np.random.randint(1,100, (5,5)) # random values will be between 1 to 99 and matrix has 5 rows and 5 columns
print(x25)

[[31 50 99 29 44]
 [ 2 14 39 59 88]
 [65 85 86 92 62]
 [68 96 35 71 91]
 [95 84 34 30 50]]


In [6]:
xseq1 = np.arange(1, 101, 4)  # values from 1 to 100 and gap is 4
print(xseq1.size, "elements")
print('-- 1D Matrix--')
print(xseq1)

print("=>1D MATRIX RESHAPED TO 2D")
#reshaping 1D into 2D matrix
print(xseq1.reshape(5,5))

25 elements
-- 1D Matrix--
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
=>1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [7]:
xseq2 = np.linspace(1, 100, 50)  # values from 1 to 100 and gap is 4
print(xseq2.size, "elements")
print('-- 1D Matrix--')
print(xseq2)


#reshaping into 2D matrix
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))


#reshaping 2D into 3D matrix
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))


50 elements
-- 1D Matrix--
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
=>1D MATRIX RESHAPED TO 2D
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327

In [8]:
xseq2d = xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [9]:
np.ones((5,5), dtype='int')   # int has to be specified here as it takes default as floating values

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods

In [10]:
x25

array([[31, 50, 99, 29, 44],
       [ 2, 14, 39, 59, 88],
       [65, 85, 86, 92, 62],
       [68, 96, 35, 71, 91],
       [95, 84, 34, 30, 50]])

In [11]:
# first row
print(x25[0])

#last row
print(x25[-1])

#single element
print(x25[0,1])

#selecting the first column
print(x25[:, 0])

#2nd column
print(x25[:, 1])

#last column
print(x25[:, -1])

[31 50 99 29 44]
[95 84 34 30 50]
50
[31  2 65 68 95]
[50 14 85 96 84]
[44 88 62 91 50]


In [12]:
#column 0 and 1 indexes
print(x25[:, [0,1]])

[[31 50]
 [ 2 14]
 [65 85]
 [68 96]
 [95 84]]


In [28]:
#column 0 and 1 index
print(x25[:,[0,1,2]]) #[row:,col]
#same
print(x25[:, :3])

[[31 50 99]
 [ 2 14 39]
 [65 85 86]
 [68 96 35]
 [95 84 34]]
[[31 50 99]
 [ 2 14 39]
 [65 85 86]
 [68 96 35]
 [95 84 34]]


In [14]:
#print values below 20
#filtering data without numpy boolean filter(bad idea)
for i in x25:
    for j in i:
        if j<=20:
            print(j)

2
14


In [15]:
x25 <= 20 # boolean filter

array([[False, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [16]:
x25[ x25 <= 20 ]

array([ 2, 14])

In [17]:
x25[ x25 > 50]

array([99, 59, 88, 65, 85, 86, 92, 62, 68, 96, 71, 91, 95, 84])

In [18]:
(x25 > 20) & (x25 < 70)

array([[ True,  True, False,  True,  True],
       [False, False,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False,  True, False, False],
       [False, False,  True,  True,  True]])

In [19]:
x25[(x25 > 20) & (x25 < 70)]

array([31, 50, 29, 44, 39, 59, 65, 62, 68, 35, 34, 30, 50])

In [20]:
np.append(x25, [1,2,3,4,5]) #not as sexpected but works

array([31, 50, 99, 29, 44,  2, 14, 39, 59, 88, 65, 85, 86, 92, 62, 68, 96,
       35, 71, 91, 95, 84, 34, 30, 50,  1,  2,  3,  4,  5])

In [21]:
np.append(x25, np.array([[1,2,3,4,5]]), axis=0)   #the dimensions of the append array must be the same as the array in which we have to append
# axis=0 for the row to be added 


array([[31, 50, 99, 29, 44],
       [ 2, 14, 39, 59, 88],
       [65, 85, 86, 92, 62],
       [68, 96, 35, 71, 91],
       [95, 84, 34, 30, 50],
       [ 1,  2,  3,  4,  5]])

In [22]:
np.append(x25, np.array([[1],[2],[3],[4],[5]]), axis=1)
# axis =1 for the column to be added and in this case the elements must be in single entity

array([[31, 50, 99, 29, 44,  1],
       [ 2, 14, 39, 59, 88,  2],
       [65, 85, 86, 92, 62,  3],
       [68, 96, 35, 71, 91,  4],
       [95, 84, 34, 30, 50,  5]])

In [23]:
a= np.random.randint(1,100, (3,2))
b= np.random.randint(1,100, (2,3))

print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [24]:
a.T  # same as a.transpose()

array([[85, 88, 36],
       [54, 40, 40]])

# Stacking 
- horizontal stacking (hstack)
- vertical stacking (vstack)

In [25]:
print(np.hstack((a,b.T)))    

[[85 54 91 58]
 [88 40 35 24]
 [36 40  7 84]]


In [26]:
print(np.hstack((a.T,b)))

[[85 88 36 91 35  7]
 [54 40 40 58 24 84]]


In [27]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))

[[85 54]
 [88 40]
 [36 40]
 [91 58]
 [35 24]
 [ 7 84]]
[[85 88 36]
 [54 40 40]
 [91 35  7]
 [58 24 84]]


In [29]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x)
print()
print(y)

[[6 4 7]
 [4 4 9]
 [4 3 1]]

[[7 4 9]
 [9 7 9]
 [1 2 5]]


In [30]:
print('add')
print(x + y) # addition
print('sub')
print(x - y) # substraction
print('div')
print(x / y) # divide
print('element wise multiplication')
print(x * y) # element wise multiplication
print('element wise mod')
print(x % y) # element wise multiplication

add
[[13  8 16]
 [13 11 18]
 [ 5  5  6]]
sub
[[-1  0 -2]
 [-5 -3  0]
 [ 3  1 -4]]
div
[[0.85714286 1.         0.77777778]
 [0.44444444 0.57142857 1.        ]
 [4.         1.5        0.2       ]]
element wise multiplication
[[42 16 63]
 [36 28 81]
 [ 4  6  5]]
element wise mod
[[6 0 7]
 [4 4 0]
 [0 1 1]]


In [31]:
print(x.dot(y)) # mat multiplication
print()

[[ 85  66 125]
 [ 73  62 117]
 [ 56  39  68]]



In [32]:
x.sum() # sum of all values

42

In [33]:
x.sum(axis=0) # row wise sum

array([14, 11, 17])

In [34]:
x.sum(axis=1) # col wise sum

array([17, 17,  8])

In [35]:
print(x.mean()) # all
print(x.mean(axis=0)) # row
print(x.mean(axis=1)) # col

4.666666666666667
[4.66666667 3.66666667 5.66666667]
[5.66666667 5.66666667 2.66666667]


In [37]:
print(x.max()) # max value
print(x.min()) # min value 
print(x.argmax()) # index of max value
print(x.argmin()) # index of min value
print(x.flatten()[4]) # accessing the index value given by argmax()

9
1
5
8
4


In [36]:
np.median(x) # some function are called using np, if not avialable through the variable

4.0